<a href="https://colab.research.google.com/github/Saumya7verma/Machine-Learning/blob/main/Emotion_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df = pd.read_csv("train.txt", sep=';', names=['text', 'emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df['emotion'].value_counts()

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [5]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    return text

df['text'] = df['text'].apply(clean_text)

In [6]:
X = df['text']
y = df['emotion']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [8]:
tfidf = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1,2)
)

In [9]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [10]:
model = LogisticRegression(
    max_iter=200,
    class_weight='balanced'
)

model.fit(X_train_tfidf, y_train)

LogisticRegression(class_weight='balanced', max_iter=200)

In [11]:
y_pred = model.predict(X_test_tfidf)

In [12]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8928125

In [13]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       anger       0.88      0.90      0.89       427
        fear       0.87      0.83      0.85       397
         joy       0.93      0.89      0.91      1021
        love       0.77      0.93      0.85       296
     sadness       0.95      0.91      0.93       946
    surprise       0.67      0.91      0.77       113

    accuracy                           0.89      3200
   macro avg       0.85      0.89      0.87      3200
weighted avg       0.90      0.89      0.89      3200

In [14]:
message = ["I am feeling very happy today"]

message_tfidf = tfidf.transform(message)

prediction = model.predict(message_tfidf)

print("Predicted Emotion:", prediction[0])

Predicted Emotion: joy

In [15]:
message = ["I am scared of the exam"]

message_tfidf = tfidf.transform(message)

prediction = model.predict(message_tfidf)

print("Predicted Emotion:", prediction[0])

Predicted Emotion: fear

In [16]:
message = ["I hate this movie"]

message_tfidf = tfidf.transform(message)

prediction = model.predict(message_tfidf)

print("Predicted Emotion:", prediction[0])

Predicted Emotion: anger